// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/4udiwe/big-bob-pizza/order-service/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
	isgomock struct{}
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepo) Create(ctx context.Context, order entity.Order) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepoMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepo)(nil).Create), ctx, order)
}

// GetAllOrders mocks base method.
func (m *MockOrderRepo) GetAllOrders(ctx context.Context, limit, offset int) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderRepoMockRecorder) GetAllOrders(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderRepo)(nil).GetAllOrders), ctx, limit, offset)
}

// GetOrderByID mocks base method.
func (m *MockOrderRepo) GetOrderByID(ctx context.Context, orderID uuid.UUID) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderRepoMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderByID), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderRepo) GetOrdersByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]entity.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderRepoMockRecorder) GetOrdersByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderRepo)(nil).GetOrdersByUserID), ctx, userID, limit, offset)
}

// UpdateOrderDelivery mocks base method.
func (m *MockOrderRepo) UpdateOrderDelivery(ctx context.Context, orderID, deliveryID uuid.UUID, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderDelivery", ctx, orderID, deliveryID, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderDelivery indicates an expected call of UpdateOrderDelivery.
func (mr *MockOrderRepoMockRecorder) UpdateOrderDelivery(ctx, orderID, deliveryID, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderDelivery", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderDelivery), ctx, orderID, deliveryID, arg3)
}

// UpdateOrderPayment mocks base method.
func (m *MockOrderRepo) UpdateOrderPayment(ctx context.Context, orderID, paymentID uuid.UUID, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderPayment", ctx, orderID, paymentID, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderPayment indicates an expected call of UpdateOrderPayment.
func (mr *MockOrderRepoMockRecorder) UpdateOrderPayment(ctx, orderID, paymentID, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderPayment", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderPayment), ctx, orderID, paymentID, arg3)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepo) UpdateOrderStatus(ctx context.Context, orderID uuid.UUID, status entity.StatusName, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatus(ctx, orderID, status, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatus), ctx, orderID, status, arg3)
}

// MockItemsRepo is a mock of ItemsRepo interface.
type MockItemsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockItemsRepoMockRecorder
	isgomock struct{}
}

// MockItemsRepoMockRecorder is the mock recorder for MockItemsRepo.
type MockItemsRepoMockRecorder struct {
	mock *MockItemsRepo
}

// NewMockItemsRepo creates a new mock instance.
func NewMockItemsRepo(ctrl *gomock.Controller) *MockItemsRepo {
	mock := &MockItemsRepo{ctrl: ctrl}
	mock.recorder = &MockItemsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemsRepo) EXPECT() *MockItemsRepoMockRecorder {
	return m.recorder
}

// InsertItems mocks base method.
func (m *MockItemsRepo) InsertItems(ctx context.Context, orderID uuid.UUID, items []entity.OrderItem) ([]entity.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertItems", ctx, orderID, items)
	ret0, _ := ret[0].([]entity.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertItems indicates an expected call of InsertItems.
func (mr *MockItemsRepoMockRecorder) InsertItems(ctx, orderID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertItems", reflect.TypeOf((*MockItemsRepo)(nil).InsertItems), ctx, orderID, items)
}

// MockOutboxRepo is a mock of OutboxRepo interface.
type MockOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepoMockRecorder
	isgomock struct{}
}

// MockOutboxRepoMockRecorder is the mock recorder for MockOutboxRepo.
type MockOutboxRepoMockRecorder struct {
	mock *MockOutboxRepo
}

// NewMockOutboxRepo creates a new mock instance.
func NewMockOutboxRepo(ctrl *gomock.Controller) *MockOutboxRepo {
	mock := &MockOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepo) EXPECT() *MockOutboxRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepo) Create(ctx context.Context, ev entity.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepoMockRecorder) Create(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepo)(nil).Create), ctx, ev)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
	isgomock struct{}
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// AddToActive mocks base method.
func (m *MockCacheRepo) AddToActive(ctx context.Context, ord *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToActive", ctx, ord)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToActive indicates an expected call of AddToActive.
func (mr *MockCacheRepoMockRecorder) AddToActive(ctx, ord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToActive", reflect.TypeOf((*MockCacheRepo)(nil).AddToActive), ctx, ord)
}

// AddToStatus mocks base method.
func (m *MockCacheRepo) AddToStatus(ctx context.Context, status string, ordID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToStatus", ctx, status, ordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToStatus indicates an expected call of AddToStatus.
func (mr *MockCacheRepoMockRecorder) AddToStatus(ctx, status, ordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToStatus", reflect.TypeOf((*MockCacheRepo)(nil).AddToStatus), ctx, status, ordID)
}

// AddUserActive mocks base method.
func (m *MockCacheRepo) AddUserActive(ctx context.Context, userID, ordID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserActive", ctx, userID, ordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserActive indicates an expected call of AddUserActive.
func (mr *MockCacheRepoMockRecorder) AddUserActive(ctx, userID, ordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserActive", reflect.TypeOf((*MockCacheRepo)(nil).AddUserActive), ctx, userID, ordID)
}

// Delete mocks base method.
func (m *MockCacheRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheRepo)(nil).Delete), ctx, id)
}

// GetActiveOrders mocks base method.
func (m *MockCacheRepo) GetActiveOrders(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrders", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrders indicates an expected call of GetActiveOrders.
func (mr *MockCacheRepoMockRecorder) GetActiveOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrders", reflect.TypeOf((*MockCacheRepo)(nil).GetActiveOrders), ctx)
}

// GetByID mocks base method.
func (m *MockCacheRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCacheRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCacheRepo)(nil).GetByID), ctx, id)
}

// GetByStatus mocks base method.
func (m *MockCacheRepo) GetByStatus(ctx context.Context, status string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockCacheRepoMockRecorder) GetByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockCacheRepo)(nil).GetByStatus), ctx, status)
}

// GetUserActiveOrders mocks base method.
func (m *MockCacheRepo) GetUserActiveOrders(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveOrders", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveOrders indicates an expected call of GetUserActiveOrders.
func (mr *MockCacheRepoMockRecorder) GetUserActiveOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveOrders", reflect.TypeOf((*MockCacheRepo)(nil).GetUserActiveOrders), ctx, userID)
}

// RemoveFromActive mocks base method.
func (m *MockCacheRepo) RemoveFromActive(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromActive", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromActive indicates an expected call of RemoveFromActive.
func (mr *MockCacheRepoMockRecorder) RemoveFromActive(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromActive", reflect.TypeOf((*MockCacheRepo)(nil).RemoveFromActive), ctx, id)
}

// RemoveFromStatus mocks base method.
func (m *MockCacheRepo) RemoveFromStatus(ctx context.Context, status string, ordID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromStatus", ctx, status, ordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromStatus indicates an expected call of RemoveFromStatus.
func (mr *MockCacheRepoMockRecorder) RemoveFromStatus(ctx, status, ordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromStatus", reflect.TypeOf((*MockCacheRepo)(nil).RemoveFromStatus), ctx, status, ordID)
}

// RemoveUserActive mocks base method.
func (m *MockCacheRepo) RemoveUserActive(ctx context.Context, userID, ordID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserActive", ctx, userID, ordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserActive indicates an expected call of RemoveUserActive.
func (mr *MockCacheRepoMockRecorder) RemoveUserActive(ctx, userID, ordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserActive", reflect.TypeOf((*MockCacheRepo)(nil).RemoveUserActive), ctx, userID, ordID)
}

// Save mocks base method.
func (m *MockCacheRepo) Save(ctx context.Context, ord *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, ord)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCacheRepoMockRecorder) Save(ctx, ord any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCacheRepo)(nil).Save), ctx, ord)
}

