{
 "title": "Big Bob Pizza logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Gateway logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"gateway\"} |= ``"
    }
   ]
  },
  {
   "title": "Menu service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"menu\"} |= ``"
    }
   ]
  },
  {
   "title": "Payments service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"payment\"} |= ``"
    }
   ]
  },
  {
   "title": "Payments service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"analytics\"} |= ``"
    }
   ]
  },
  {
   "title": "Order service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"order\"} |= ``"
    }
   ]
  }
 ]
}